### ISSUE TITLE
Jest test error

### ISSUE THREAD

**Issue by ursualexandr** [davidyaha/graphql-redis-subscriptions#213]
I'm getting an error when I try implementng a test for pubsub publishing:

```
     MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
          at Socket.<anonymous> (/Users/alex/workspace/node_modules/ioredis/built/redis/event_handler.js:108:37)
          at Object.onceWrapper (events.js:300:26)
          at Socket.emit (events.js:210:5)
          at TCP.<anonymous> (net.js:658:12)
```

Everything works fine when using/testing manually service on my localhost but when I'm trying to run it from jest looks like it fails to connect to Redis or cannot publish to it, has anyone run into similar issue?

```
const options = {
  host: 'localhost',
  port: 6379,
  retryStrategy: (times: any) => {
    // reconnect after
    return Math.min(times * 50, 2000);
  }
};
export const pubsub = new RedisPubSub({
  publisher: new Redis(options),
  subscriber: new Redis(options)
});
```

**Comment by davidyaha** [comment]
Hey @ursualexandr, have you tried running the integration tests supplied with this package or is it your own testing suite?
