### ISSUE TITLE
Error: There is no subscription of id "*"

### ISSUE THREAD

**Issue by filoozom** [davidyaha/graphql-redis-subscriptions#225]
Hi, I keep getting the following error:

```
(node:10676) UnhandledPromiseRejectionWarning: Error: There is no subscription of id "19"
    at RedisPubSub.unsubscribe (C:\Users\Philippe\Projects\api\node_modules\graphql-redis-subscriptions\dist\redis-pubsub.js:125:19)
    at PubSubAsyncIterator.unsubscribeAll (C:\Users\Philippe\Projects\api\node_modules\graphql-redis-subscriptions\dist\pubsub-async-iterator.js:150:25)
    at PubSubAsyncIterator.<anonymous> (C:\Users\Philippe\Projects\api\node_modules\graphql-redis-subscriptions\dist\pubsub-async-iterator.js:128:28)
    at step (C:\Users\Philippe\Projects\api\node_modules\graphql-redis-subscriptions\dist\pubsub-async-iterator.js:32:23)
    at Object.next (C:\Users\Philippe\Projects\api\node_modules\graphql-redis-subscriptions\dist\pubsub-async-iterator.js:13:53)
    at fulfilled (C:\Users\Philippe\Projects\api\node_modules\graphql-redis-subscriptions\dist\pubsub-async-iterator.js:4:58)
(node:10676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
```

This is on a new setup that worked perfectly with the generic `PubSub` implementation of `apollo-server`. Am I doing something wrong?

**Comment by davidyaha** [comment]
Hey @filoozom do you use the apollo's subscriptions-transport-ws client?
AFAIK the id is auto-sent to the server if you're using that. 
If you're not using the ws transport and you don't want to, you might want to take a peek into how this package `unsubscribe` is implemented and suggest a fix.

**Comment by davidyaha** [comment]
@filoozom Sorry for the last reply. Deleted it so the history of this thread would be clear.
Could you show your setup code and describe at what point you get this error?
Thanks

**Comment by filoozom** [comment]
@davidyaha Hi, sorry, forgot to close this. Actually, the error was simply that I tried (due to some bug) to subscribe to the `undefined` topic, which understandably doesn't work. Might have been nice to have a warning though!

**Comment by davidyaha** [comment]
Glad to hear it was fixed. I Would happily merge a PR for that warning :)
